# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=70)),
                ('abstract', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('m', 'markdown'), ('h', 'html')], max_length=1)),
                ('show_comment', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('modified_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('visible', models.CharField(choices=[('p', 'public'), ('l', 'login'), ('s', 'staff'), ('d', 'draft')], max_length=1)),
                ('sticky', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(default='postyp', max_length=32)),
                ('blog_desc', models.CharField(default='', max_length=140)),
                ('blog_nav_tags', models.CharField(default='', max_length=256)),
                ('google_analytics_id', models.CharField(max_length=16, null=True)),
                ('comment_system', models.CharField(choices=[('i', 'buildin'), ('d', 'disqus')], max_length=1)),
                ('disqus_id', models.CharField(max_length=32)),
                ('new_post_content_type', models.CharField(choices=[('m', 'markdown'), ('h', 'html')], max_length=1)),
                ('about_page_html', models.TextField(default='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogSetting',
        ),
    ]
