# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blog', '0002_auto_20170103_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='about_page_html',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='comment_system',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='visible',
            field=models.CharField(choices=[('p', 'public'), ('d', 'draft')], max_length=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='disqus_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.Site'),
        ),
    ]
