# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170107_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='_domain',
            field=models.CharField(db_column='domain', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='_name',
            field=models.CharField(db_column='name', max_length=50),
        ),
    ]
