# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170107_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='_domain',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='site',
        ),
        migrations.AddField(
            model_name='blog',
            name='domain',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
