# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170105_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='rss',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='sitemap',
            field=models.BooleanField(default=True),
        ),
    ]
