# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170106_0103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Blog',
        ),
    ]
