# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170106_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_nav_tags',
            new_name='tags_nav',
        ),
        migrations.AddField(
            model_name='blog',
            name='urls_nav',
            field=models.CharField(default='', max_length=256),
        ),
    ]
