# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170106_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='theme',
            field=models.CharField(default='default', max_length=16),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default='MultBlog', max_length=32),
        ),
        migrations.AlterField(
            model_name='blog',
            name='new_post_content_type',
            field=models.CharField(choices=[('m', 'markdown'), ('h', 'html')], default='m', max_length=1),
        ),
    ]
