# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170106_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pages_url_prefix',
            field=models.CharField(default='pages', max_length=12),
        ),
        migrations.AddField(
            model_name='blog',
            name='posts_url_prefix',
            field=models.CharField(default='posts', max_length=12),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='blog',
            name='disqus_id',
            field=models.CharField(blank=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags_nav',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='blog',
            name='urls_nav',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
