# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('blog', '0007_auto_20170107_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='site_ptr',
        ),
        migrations.AddField(
            model_name='blog',
            name='domain',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
