# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170106_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-last_modified_time', 'create_time']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='show_comment',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags_nav',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='urls_nav',
        ),
        migrations.RemoveField(
            model_name='post',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visible',
        ),
        migrations.AddField(
            model_name='blog',
            name='navs',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('p', 'public'), ('d', 'draft')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='disqus_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='new_post_content_type',
            field=models.CharField(choices=[('e', 'Editor.md'), ('m', 'marked.js'), ('h', 'html')], default='e', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('e', 'Editor.md'), ('m', 'marked.js'), ('h', 'html')], max_length=1),
        ),
    ]
