# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170106_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='new_post_content_type',
            new_name='default_editor',
        ),
    ]
