# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170107_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.CharField(choices=[('a', 'Anyone'), ('l', 'Login'), ('x', 'Close'), ('d', 'disqus')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='domain',
            field=models.CharField(help_text='Only this domain can access this blog', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, help_text='as post url', max_length=128, unique=True),
        ),
    ]
