# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170108_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='default_editor',
            field=models.CharField(choices=[('m', 'marked.js'), ('h', 'html')], default='e', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('m', 'marked.js'), ('h', 'html')], max_length=1),
        ),
    ]
