# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170108_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pages_url_prefix',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='posts_url_prefix',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='site',
        ),
        migrations.AlterField(
            model_name='blog',
            name='default_editor',
            field=models.CharField(choices=[('m', 'marked.js'), ('h', 'html')], default='m', max_length=1),
        ),
    ]
