# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170227_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='rendered_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
