# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_auto_20170302_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(default='', max_length=64)),
                ('content', models.TextField()),
                ('login_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('tag_type', models.CharField(choices=[('u', 'User tag'), ('s', 'System auto tag')], default='u', max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='comment_enable',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='default_editor',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='disqus_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='google_analytics_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='accessibility',
            field=models.CharField(choices=[('a', 'Anyone'), ('l', 'Login'), ('x', 'Close'), ('p', 'Password')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_html',
            field=models.TextField(blank=True, default='', help_text='insert to tail of body'),
        ),
        migrations.AddField(
            model_name='blog',
            name='custom_comment_html',
            field=models.TextField(blank=True, default='', help_text='work if comments=c'),
        ),
        migrations.AddField(
            model_name='blog',
            name='custom_theme_area_html',
            field=models.TextField(blank=True, default='', help_text='insert to place theme defined'),
        ),
        migrations.AddField(
            model_name='blog',
            name='head_html',
            field=models.TextField(blank=True, default='', help_text='insert to tail of head'),
        ),
        migrations.AddField(
            model_name='blog',
            name='password_hash',
            field=models.CharField(default='', help_text='Need if accessibility=p', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.CharField(choices=[('a', 'Anyone'), ('l', 'Login'), ('x', 'Close'), ('c', 'Custom')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(blank=True, default='This is my new blog.', max_length=140),
        ),
        migrations.AlterField(
            model_name='blog',
            name='navs',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
