# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_blog_custom_theme_area_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='blog',
        ),
        migrations.AddField(
            model_name='post',
            name='template_name',
            field=models.CharField(default='default', max_length=24),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, help_text='as url', max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
