# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170313_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='absolute_url',
            field=models.CharField(default='', help_text='To generate sitemap link, e.g. http://example.com/', max_length=128),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(blank=True, default='This is my new blog.', help_text='HTML', max_length=140),
        ),
        migrations.AlterField(
            model_name='blog',
            name='domain',
            field=models.CharField(help_text='Only this domain can access this blog, e.g. emample.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='rendered_html',
            field=models.TextField(default=''),
        ),
    ]
