# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20170318_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.TextField(default=''),
        ),
    ]
