# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_post_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_type',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=42),
        ),
    ]
