# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170103_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default='', max_length=10),
        ),
    ]
