# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
    ]
